### ISSUE TITLE
Who provides an available public server address?

### ISSUE THREAD

**Issue by Waterman178** [vrtadmin/FIRST-plugin-ida#27] opened 2019-10-15 10:04 UTC
Ida can't connect to first-plugin.us

**Comment by xabiugarte** [comment] 2019-10-15 10:10
Hi Waterman178,

the current public facing address for First is https://first.talosintelligence.com/ 

We have just noticed that the code is pointing to the old server (https://github.com/vrtadmin/FIRST-plugin-ida/blob/10b8403484ddd5881a43facc4e29d4b9cc661f92/first_plugin_ida/first.py#L1702), we will update it immediately.

Thanks for reporting this,

**Comment by Waterman178** [comment] 2019-10-15 10:24
![QQ截图20191015181449](https://user-images.githubusercontent.com/14991217/66823250-6ddfac80-ef78-11e9-96e3-acd06cbd35e4.png)
what is the problem？
![5555](https://user-images.githubusercontent.com/14991217/66823468-e8a8c780-ef78-11e9-8b30-e01aee22264d.png)
Do I have to register first? Follow the prompts, after I enter the handle, navigate this page to Google. After I have selected one of my Google accounts, it prompts this:"Server Error (500)"

**Comment by xabiugarte** [comment] 2019-10-15 10:48
The host should be "first.talosintelligence.com"
The protocol should be https, and port 443.

You will need a valid API key. In order to obtain it, you just need to register just like you did. Specify a handle (only alphanumeric characters and underscores), and log in into your google account. I just did it myself with a fresh account, and I didn't have any problem (no Server Error (500)). Please make sure that the google account is allowed to log in in external services (it is not a company managed account with restrictions).

If the problem persists, please try to do it with a fresh gmail account, and if it still persists, please let us know the detailed steps followed so that we can try to reproduce the error.

**Comment by xabiugarte** [comment] 2019-10-15 10:52
The following commit fixes the default server address:
https://github.com/vrtadmin/FIRST-plugin-ida/commit/567d7abb83a81e5e44aa730f5eb3d483e2b7dc01

**Comment by Waterman178** [comment] 2019-10-15 11:48
> 以下提交可修复默认服务器地址：
> [567d7ab](https://github.com/vrtadmin/FIRST-plugin-ida/commit/567d7abb83a81e5e44aa730f5eb3d483e2b7dc01)

I know the reason. If the Google account is not in English, the server will return an error.

**Comment by xabiugarte** [comment] 2019-10-15 11:54
Ok, it looks like it could be a character encoding issue. I will close this issue and open a new one to keep track of this problem.

I am glad you managed to make it work.

**Closed by xabiugarte** 2019-10-15 11:54 UTC
