### ISSUE TITLE
Can't get "apis"  ,it is an  empty list.

### ISSUE THREAD

**Issue by pwd9527** [vrtadmin/FIRST-plugin-ida#15] opened 2017-12-29 04:23 UTC
hi,

Sending: {'crc32': 3728824636L,
 'functions': '{"4199328": {"comment": "", "opcodes": "U1ZXVYPE+IvYi/uLMotDCDvwcmyLzgNKBIvoA2sMO813XjvwdRuLQgQBQwiLQgQpQwyDewwAdUSLw+g1////6zuLCotyBAPOi/gDeww7z3UFKXMM6yaLCgNKBIkMJCv5iXwkBIsSK9CJUwyL1IvD6ND+//+EwHUEM8DrDLAB6wiLGzv7dYUzwFlaXV9eW8M=", "name": "sub_4013A0", "apis": [], "architecture": "intel32", "prototype": "", "id": null}}',

"apis": []    ??

 "id": null ??

thanks

**Comment by pwd9527** [comment] 2017-12-29 05:23
The sub_4013A0 function does have many "API" calls

**Comment by demonduck** [comment] 2018-01-02 12:04
Unfortunately without an example sample hash or an IDB, all I can do is speculate why this is occurring. If you can supply either one of those then I can track down what is happening. 

The "id" field is used to keep track if/when metadata from FIRST is applied to your local function. That way updates can be pulled when you select to update your IDB's metadata

**Comment by pwd9527** [comment] 2018-01-09 03:53
If you open IDA first, then drag the sample to IDA. This situation is problematic.

The FIRST. Initialize () function is too early.  IAT is empty  .So "apis = []"

**Comment by demonduck** [comment] 2018-01-09 14:23
This should be fixed in the latest commit to the dev branch (https://github.com/vrtadmin/FIRST-plugin-ida/commit/5e4c7f00333a44e65086297df3f98986f5d7fa17). Once FIRST-server 0.1 is released this version will be pushed to the master branch. The plugin in the dev branch should work with both versions. 

Thanks for creating this issue, please reopen if the problem is not fixed.

**Closed by demonduck** 2018-01-09 14:23 UTC
